package id.go.djp.cm.bridge.sidjp.model;

import java.math.BigDecimal;

public class MsKpp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MS_KPP.ID
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MS_KPP.VERSION
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MS_KPP.ALAMATKPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    private String alamatkpp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MS_KPP.KODE_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    private String kodeKpp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MS_KPP.NAMA_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    private String namaKpp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MS_KPP.ID
     *
     * @return the value of MS_KPP.ID
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MS_KPP.ID
     *
     * @param id the value for MS_KPP.ID
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MS_KPP.VERSION
     *
     * @return the value of MS_KPP.VERSION
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MS_KPP.VERSION
     *
     * @param version the value for MS_KPP.VERSION
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MS_KPP.ALAMATKPP
     *
     * @return the value of MS_KPP.ALAMATKPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public String getAlamatkpp() {
        return alamatkpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MS_KPP.ALAMATKPP
     *
     * @param alamatkpp the value for MS_KPP.ALAMATKPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setAlamatkpp(String alamatkpp) {
        this.alamatkpp = alamatkpp == null ? null : alamatkpp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MS_KPP.KODE_KPP
     *
     * @return the value of MS_KPP.KODE_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public String getKodeKpp() {
        return kodeKpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MS_KPP.KODE_KPP
     *
     * @param kodeKpp the value for MS_KPP.KODE_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setKodeKpp(String kodeKpp) {
        this.kodeKpp = kodeKpp == null ? null : kodeKpp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MS_KPP.NAMA_KPP
     *
     * @return the value of MS_KPP.NAMA_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public String getNamaKpp() {
        return namaKpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MS_KPP.NAMA_KPP
     *
     * @param namaKpp the value for MS_KPP.NAMA_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setNamaKpp(String namaKpp) {
        this.namaKpp = namaKpp == null ? null : namaKpp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsKpp other = (MsKpp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getAlamatkpp() == null ? other.getAlamatkpp() == null : this.getAlamatkpp().equals(other.getAlamatkpp()))
            && (this.getKodeKpp() == null ? other.getKodeKpp() == null : this.getKodeKpp().equals(other.getKodeKpp()))
            && (this.getNamaKpp() == null ? other.getNamaKpp() == null : this.getNamaKpp().equals(other.getNamaKpp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getAlamatkpp() == null) ? 0 : getAlamatkpp().hashCode());
        result = prime * result + ((getKodeKpp() == null) ? 0 : getKodeKpp().hashCode());
        result = prime * result + ((getNamaKpp() == null) ? 0 : getNamaKpp().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", version=").append(version);
        sb.append(", alamatkpp=").append(alamatkpp);
        sb.append(", kodeKpp=").append(kodeKpp);
        sb.append(", namaKpp=").append(namaKpp);
        sb.append("]");
        return sb.toString();
    }
}