package id.go.djp.cm.bridge.sidjp.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MsKppExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public MsKppExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(BigDecimal value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(BigDecimal value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(BigDecimal value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(BigDecimal value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<BigDecimal> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<BigDecimal> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andAlamatkppIsNull() {
            addCriterion("ALAMATKPP is null");
            return (Criteria) this;
        }

        public Criteria andAlamatkppIsNotNull() {
            addCriterion("ALAMATKPP is not null");
            return (Criteria) this;
        }

        public Criteria andAlamatkppEqualTo(String value) {
            addCriterion("ALAMATKPP =", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppNotEqualTo(String value) {
            addCriterion("ALAMATKPP <>", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppGreaterThan(String value) {
            addCriterion("ALAMATKPP >", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppGreaterThanOrEqualTo(String value) {
            addCriterion("ALAMATKPP >=", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppLessThan(String value) {
            addCriterion("ALAMATKPP <", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppLessThanOrEqualTo(String value) {
            addCriterion("ALAMATKPP <=", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppLike(String value) {
            addCriterion("ALAMATKPP like", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppNotLike(String value) {
            addCriterion("ALAMATKPP not like", value, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppIn(List<String> values) {
            addCriterion("ALAMATKPP in", values, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppNotIn(List<String> values) {
            addCriterion("ALAMATKPP not in", values, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppBetween(String value1, String value2) {
            addCriterion("ALAMATKPP between", value1, value2, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andAlamatkppNotBetween(String value1, String value2) {
            addCriterion("ALAMATKPP not between", value1, value2, "alamatkpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppIsNull() {
            addCriterion("KODE_KPP is null");
            return (Criteria) this;
        }

        public Criteria andKodeKppIsNotNull() {
            addCriterion("KODE_KPP is not null");
            return (Criteria) this;
        }

        public Criteria andKodeKppEqualTo(String value) {
            addCriterion("KODE_KPP =", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppNotEqualTo(String value) {
            addCriterion("KODE_KPP <>", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppGreaterThan(String value) {
            addCriterion("KODE_KPP >", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppGreaterThanOrEqualTo(String value) {
            addCriterion("KODE_KPP >=", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppLessThan(String value) {
            addCriterion("KODE_KPP <", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppLessThanOrEqualTo(String value) {
            addCriterion("KODE_KPP <=", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppLike(String value) {
            addCriterion("KODE_KPP like", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppNotLike(String value) {
            addCriterion("KODE_KPP not like", value, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppIn(List<String> values) {
            addCriterion("KODE_KPP in", values, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppNotIn(List<String> values) {
            addCriterion("KODE_KPP not in", values, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppBetween(String value1, String value2) {
            addCriterion("KODE_KPP between", value1, value2, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andKodeKppNotBetween(String value1, String value2) {
            addCriterion("KODE_KPP not between", value1, value2, "kodeKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppIsNull() {
            addCriterion("NAMA_KPP is null");
            return (Criteria) this;
        }

        public Criteria andNamaKppIsNotNull() {
            addCriterion("NAMA_KPP is not null");
            return (Criteria) this;
        }

        public Criteria andNamaKppEqualTo(String value) {
            addCriterion("NAMA_KPP =", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppNotEqualTo(String value) {
            addCriterion("NAMA_KPP <>", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppGreaterThan(String value) {
            addCriterion("NAMA_KPP >", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppGreaterThanOrEqualTo(String value) {
            addCriterion("NAMA_KPP >=", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppLessThan(String value) {
            addCriterion("NAMA_KPP <", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppLessThanOrEqualTo(String value) {
            addCriterion("NAMA_KPP <=", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppLike(String value) {
            addCriterion("NAMA_KPP like", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppNotLike(String value) {
            addCriterion("NAMA_KPP not like", value, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppIn(List<String> values) {
            addCriterion("NAMA_KPP in", values, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppNotIn(List<String> values) {
            addCriterion("NAMA_KPP not in", values, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppBetween(String value1, String value2) {
            addCriterion("NAMA_KPP between", value1, value2, "namaKpp");
            return (Criteria) this;
        }

        public Criteria andNamaKppNotBetween(String value1, String value2) {
            addCriterion("NAMA_KPP not between", value1, value2, "namaKpp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MS_KPP
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 19 14:55:02 ICT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}