package id.go.djp.cm.bridge.sidjp.mapper;

import id.go.djp.cm.bridge.sidjp.model.MasterJenisSurat;
import id.go.djp.cm.bridge.sidjp.model.MasterJenisSuratExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MasterJenisSuratMapper extends CommonMapper<MasterJenisSurat,BigDecimal>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int countByExample(MasterJenisSuratExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int deleteByExample(MasterJenisSuratExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int insert(MasterJenisSurat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int insertSelective(MasterJenisSurat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    List<MasterJenisSurat> selectByExampleWithRowbounds(MasterJenisSuratExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    List<MasterJenisSurat> selectByExample(MasterJenisSuratExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    MasterJenisSurat selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int updateByExampleSelective(@Param("record") MasterJenisSurat record, @Param("example") MasterJenisSuratExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int updateByExample(@Param("record") MasterJenisSurat record, @Param("example") MasterJenisSuratExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int updateByPrimaryKeySelective(MasterJenisSurat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    int updateByPrimaryKey(MasterJenisSurat record);
}