package id.go.djp.cm.bridge.sidjp.mapper;

import id.go.djp.cm.bridge.sidjp.model.MsKpp;
import id.go.djp.cm.bridge.sidjp.model.MsKppExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MsKppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int countByExample(MsKppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int deleteByExample(MsKppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int insert(MsKpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int insertSelective(MsKpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    List<MsKpp> selectByExampleWithRowbounds(MsKppExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    List<MsKpp> selectByExample(MsKppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    MsKpp selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int updateByExampleSelective(@Param("record") MsKpp record, @Param("example") MsKppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int updateByExample(@Param("record") MsKpp record, @Param("example") MsKppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int updateByPrimaryKeySelective(MsKpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MS_KPP
     *
     * @mbggenerated Tue Nov 19 14:55:02 ICT 2013
     */
    int updateByPrimaryKey(MsKpp record);
}