package id.go.djp.cm.bridge.sidjp.model;

import java.math.BigDecimal;

public class MasterJenisSurat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MASTER_JENIS_SURAT.ID
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MASTER_JENIS_SURAT.VERSION
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MASTER_JENIS_SURAT.KODE
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    private String kode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MASTER_JENIS_SURAT.NAMA
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    private String nama;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MASTER_JENIS_SURAT.ID
     *
     * @return the value of MASTER_JENIS_SURAT.ID
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MASTER_JENIS_SURAT.ID
     *
     * @param id the value for MASTER_JENIS_SURAT.ID
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MASTER_JENIS_SURAT.VERSION
     *
     * @return the value of MASTER_JENIS_SURAT.VERSION
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MASTER_JENIS_SURAT.VERSION
     *
     * @param version the value for MASTER_JENIS_SURAT.VERSION
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MASTER_JENIS_SURAT.KODE
     *
     * @return the value of MASTER_JENIS_SURAT.KODE
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public String getKode() {
        return kode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MASTER_JENIS_SURAT.KODE
     *
     * @param kode the value for MASTER_JENIS_SURAT.KODE
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public void setKode(String kode) {
        this.kode = kode == null ? null : kode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MASTER_JENIS_SURAT.NAMA
     *
     * @return the value of MASTER_JENIS_SURAT.NAMA
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MASTER_JENIS_SURAT.NAMA
     *
     * @param nama the value for MASTER_JENIS_SURAT.NAMA
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    public void setNama(String nama) {
        this.nama = nama == null ? null : nama.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MasterJenisSurat other = (MasterJenisSurat) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getKode() == null ? other.getKode() == null : this.getKode().equals(other.getKode()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getKode() == null) ? 0 : getKode().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MASTER_JENIS_SURAT
     *
     * @mbggenerated Fri Oct 25 16:15:57 WIT 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", version=").append(version);
        sb.append(", kode=").append(kode);
        sb.append(", nama=").append(nama);
        sb.append("]");
        return sb.toString();
    }
}